# Generated by Django 4.2 on 2023-05-16 03:25

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicqrcode', '0003_rename_book_choice_dynamicqrcode_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicqrcode',
            name='type',
        ),
        migrations.AddField(
            model_name='dynamicqrcode',
            name='another_field',
            field=model_utils.fields.StatusField(choices=[('English', 'English'), ('Nepali', 'Nepali')], default='English', max_length=100, no_check_for_status=True),
        ),
    ]
